# Generated by Django 4.2.7 on 2023-11-29 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/', verbose_name='image_product')),
                ('name', models.CharField(max_length=100, null=True)),
                ('about', models.TextField(verbose_name='about_product')),
                ('price', models.IntegerField()),
                ('gender', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default='men', max_length=5)),
                ('status', models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], default='draft', max_length=30, verbose_name='status')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
