# Generated by Django 4.2.7 on 2023-11-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_gender_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='1', upload_to='posts/', verbose_name='image_product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='2', upload_to='posts/', verbose_name='image_product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='3', upload_to='posts/', verbose_name='image_product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default='men', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], default='draft', max_length=30, verbose_name='status'),
        ),
    ]
