# Generated by Django 4.2.7 on 2023-12-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_product_gender_category_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default='men', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], default='draft', max_length=30, verbose_name='status'),
        ),
    ]
